#!/bin/bash
# Combine anasum files from run lists
#
set -e

if [[ $# -lt 2 ]]; then
echo "
  Combine anasum file from run lists
  ./anasum_yearly.sh <runparameter file> <anasum-run-wise directory>

  Depends on the runlists generated by runlist_generator_from_anasum_log.sh

"
exit
fi

# read runparameter file
if [[ ! -e ${1} ]]; then
   echo "Error, runparameter file not found: ${1}"
   exit
fi
# Eventdisplay version
VERSION=$(grep VERSION ${1} | awk '{print $3}')
# Analysis type
ANALYSISTYPE="AP"
if [[ ! -z  $VERITAS_ANALYSIS_TYPE ]]; then
    ANALYSISTYPE="${VERITAS_ANALYSIS_TYPE:0:2}"
fi
# Source name
OBJECT=($(grep SOURCE ${1} | grep "*" | awk '{print $3}'))
#########################
# run mode
INDIR="$2"
# cut
CUT="$(basename $INDIR)"
echo "CUT $CUT"
# Directory for data files
DDIR="$VERITAS_USER_DATA_DIR/analysis/Results/${VERSION}/${ANALYSISTYPE}/${OBJECT}/${CUT}"
mkdir -p "$DDIR"
echo $DDIR

# run lists
VDIR=$(readlink -f ../../../../EventDisplay_Release_${VERSION}/${OBJECT}/runlists)
RLISTS="$(ls -1 ${VDIR}/*.dat)"

# run parameter
RUNP="$(pwd)/runparameter.dat"

cd "${EVNDISPSCRIPTS}"

for R in $RLISTS; do
    echo "RUNLIST $R"

    FFIL=$(basename $R .dat)
    echo $FFIL
    ANASUMFIL="$DDIR/anasum_${FFIL/runlist_/}"

    echo "ANASUM output $ANASUMFIL"

    ./ANALYSIS.anasum_combine.sh \
           $R \
           $INDIR \
           ${ANASUMFIL}.combined \
           $RUNP
done
