name: eventdisplay-release-tests
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - matplotlib
  - pandoc
  - pre-commit
  - towncrier

# cheat sheet
# create: conda env create -f environment.yml
# activate: conda activate eventdisplay-release-tests
# update (conda/mamba): conda env update -f environment.yml --prune
# update (micromamba): micromamba update -f environment.yml
# update (micromamba): micromamba update -n eventdisplay-release-tests -f environment.yml
