name: eventdisplay-release-tests
channels:
  - conda-forge
dependencies:
  - pandoc
  - pre-commit

# cheatsheet
# create: conda env create -f environment.yml
# activate: conda activate eventdisplay-release-tests
# update (conda/mamba): conda env update -f environment.yml --prune
# update (micromamba): micromamba update -f environment.yml
