[tool.towncrier]
name = "EventDisplay_ReleaseTests_code"
directory = "documentation/changes"
filename = "CHANGELOG.md"
underlines = [ "", "", "" ]
title_format = "## [{version}](https://github.com/VERITAS-Observatory/EventDisplay_ReleaseTests_code/releases/tag/{version}) - {project_date}"
issue_format = "[#{issue}](https://github.com/VERITAS-Observatory/EventDisplay_ReleaseTests_code/issues/{issue})"
start_string = "<!-- towncrier release notes start -->\n"

[tool.towncrier.fragment.feature]
name = "New Features"
showcontent = true

[tool.towncrier.fragment.bugfix]
name = "Bugfixes"
showcontent = true

[tool.towncrier.fragment.maintenance]
name = "Maintenance"
showcontent = true

[tool.towncrier.fragment.doc]
name = "Documentation"
showcontent = true
