#!/bin/bash
# Combine anasum files from run lists
#
set -e

if [[ $# -lt 2 ]]; then
echo "
  Combine anasum file from run lists
  ./anasum_from_runlist.sh <runparameter file> <anasum-run-wise directory (without CUT and '_')>

  Depends on the runlists generated by runlist_generator_from_anasum_log.sh

"
exit
fi

# read runparameter file
if [[ ! -e ${1} ]]; then
   echo "Error, runparameter file not found: ${1}"
   exit
fi
# Eventdisplay version
VERSION=$(grep VERSION ${1} | awk '{print $3}')
# Analysis type
ANALYSISTYPE="AP"
if [[ ! -z  $VERITAS_ANALYSIS_TYPE ]]; then
    ANALYSISTYPE="${VERITAS_ANALYSIS_TYPE:0:2}"
fi
echo "VERSION $VERSION ANALYSISTYPE $ANALYSISTYPE"
# Major epoch
MEPOCH=($(grep MAJOREPOCH ${1} | grep "*" | awk '{print $3}'))
# Source name
OBJECT=($(grep SOURCE ${1} | grep "*" | awk '{print $3}'))
CUTS=""
# CUT lines contain both a full cut token and a short alias.
# Always consume the alias in field 4 to avoid mixing naming schemes.
while IFS= read -r cut_alias; do
    if [[ -z "$cut_alias" ]]; then
        echo "Error, malformed '* CUT' line in runparameter file: ${1}"
        exit 1
    fi
    CUTS="$CUTS $cut_alias"
done < <(awk '/^\* CUT[[:space:]]+/ { if (NF < 4) { print ""; next } print $4 }' "${1}")

if [[ -z "$CUTS" ]]; then
    echo "Error, no CUT aliases (field 4 of '* CUT' lines) found in runparameter file: ${1}"
    exit 1
fi
echo "CUTS $CUTS"

# run lists
VDIR=$(readlink -f ../../../../EventDisplay_Release_${VERSION}/${OBJECT}/runlists)
if [[ $MEPOCH == *"redHV"* ]]; then
    RLISTS="$(ls -1 ${VDIR}/*.dat | grep redHV)"
else
    RLISTS="$(ls -1 ${VDIR}/*$MEPOCH*.dat | grep -v redHV)"
fi
echo "RUNLISTS: $RLISTS"

cd "${EVNDISPSCRIPTS}"

for CUT in $CUTS; do
    echo $CUT
    INDIR="${2}_${CUT}"
    echo $INDIR
    #########################
    # Directory for data files
    DDIR="$VERITAS_USER_DATA_DIR/analysis/Results/${VERSION}/${ANALYSISTYPE}/${OBJECT}/${MEPOCH}_${CUT}"
    mkdir -p "$DDIR"
    echo $DDIR
    for R in $RLISTS; do
        echo "RUNLIST $R"

        FFIL=$(basename $R .dat)
        echo $FFIL
        ANASUMFIL="$DDIR/anasum_${FFIL/runlist_/}"

        echo "ANASUM output $ANASUMFIL"

        ./ANALYSIS.anasum_combine.sh \
               $R \
               $INDIR \
               ${ANASUMFIL}.combined
    done
done
